export * from './Contact'
export * from './Home'
export * from './Prodcuts'
export * from './Services'
export * from './Login'
export * from './NotFound'
export * from './ProductDetailPage'
export * from './Redirect'